### ISSUE TITLE
electrode 

### ISSUE THREAD

**Issue by EasonLX** [neurotech-berkeley-devices/eog-eye-tracking#1]
May I ask what electrode you use？

**Comment by ingazhur** [comment]
We used OpenBCI's gold cup electrodes!

**Comment by EasonLX** [comment]
> We used OpenBCI's gold cup electrodes!

Thank you！The project is very nice！Is there any relevant explanation for the filter circuit? I'm a novice. I'm afraid that there will be large deviation in different environments.
